name-template: 'v$NEXT_PATCH_VERSION 🎉'
tag-template: 'v$NEXT_PATCH_VERSION'
version-resolver: "git-tags"
categories:
  - title: '🚀 Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🛠 Maintenance'
    labels:
      - chore
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changes
  $CHANGES
